### ISSUE TITLE
TTFB(Time to The First Byte) 속도가 너무 느리다. 

### ISSUE THREAD

**Issue by miconblog** [rlibro/feedback#38]
## 첫번째 바이트 응답이 느린 이유는 2가지가 있을수 있다. 
1. 서버와 데이터베이스간의 네트웍 latancy 문제일 경우
2. 데이터베이스 응답이 느린 경우

## 해결방안
1. 웹서버와 데이터베이스 서버의 위치를 같은 존으로 옮긴다. 혹은 로컬로 옮긴다. 
2. 데이터베이스 쿼리가 늦는게 있는지 확인한다. 

## 추측되는 원인 
기존 페북에서 제공하던 Parse 서버를 Heroku와 mLab으로 분리하면서 서버와 데이터베이스간의 거리가 멀어져서 나타는 문제로 보임. 추후 서버와 데이터베이스를 모두 AWS로 옮기거나 무료에서 유료 요금제로 클라우드 자체를 업그레이드하는 방법도 고려해볼만함. 아님 캐시서버를 두거나.. 

## 참고문서
https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/understanding-resource-timing

**Comment by skyisle** [comment]
그러게요 방금 해보니 RedBook 응답이랑 count 응답이 6초가 넘게 걸리네요

<img width="917" alt="developer_tools_-_http___rlibro_com_" src="https://cloud.githubusercontent.com/assets/71561/13834913/25e05932-ec36-11e5-9145-0c1e250a2468.png">

**Comment by miconblog** [comment]
네, 공짜로 쓰는 mLab 문제인거 같아요. 그래서 DB를 AWS로 옮겨서 테스트해 볼 예정이에요.

**Comment by miconblog** [comment]
mLab 문제가 맞았어요. 같은 서버상에 DB를 옮겼더니 해결되네요.
