### ISSUE TITLE
버그 죽여주세요! ( 지도 삽입할 때 1개만 제대로 업로드 되고 나머지는 안되는 증상)

### ISSUE THREAD

**Issue by Aromi** [rlibro/feedback#46]
- 지도 삽입할 때 1개만 제대로 업로드 되고 나머지는 안됨. 한 개 마킹하고 지도 닫고 다시 마킹 하면 됨.
- 분명 처음 위치 마킹 하는 건데 2번으로 뜸. 아마도 검색해서 위치 추가하려할 때 문제일지도?
- 삽입이 제대로 안됨. 코드생성되고 본문에도 넣었는데 post 누르면 안뜸

**Comment by Aromi** [comment]
- 지도 삽입할 때 1개만 제대로 업로드 되고 나머지는 안됨. 한 개 마킹하고 지도 닫고 다시 마킹 하면 됨.
- 분명 처음 위치 마킹 하는 건데 2번으로 뜸. 아마도 검색해서 위치 추가하려할 때 문제일지도?

**Comment by miconblog** [comment]
다 죽였습니다.
