### ISSUE TITLE
페이스북 로그인 버튼을 눌러도 로그인이 안됨

### ISSUE THREAD

**Issue by limsungmook** [rlibro/feedback#81]
로그인 버튼을 눌러도 로그인이 되지 않습니다.
두 번째로 눌렀을 땐 로그인이 됩니다. 근데 거의 항상 첫 번째로 눌렀을 땐 실패했습니다. 버튼은 상단바 로그인 눌렀을 때나 City 안의 + Note 눌렀을 때 나오는 페이스북 로그인 눌렀을 때나 마찬가지였습니다. 
제 브라우저는 크롬입니다.

아래 gif 참고해주세요

![rlibro_fail_login](https://cloud.githubusercontent.com/assets/967597/16365912/d46c3068-3c48-11e6-8452-6720c229f697.gif)

버튼 눌렀을 때 나오는 JS 에러입니다
<img width="1228" alt="2016-06-27 9 27 27" src="https://cloud.githubusercontent.com/assets/967597/16365956/83cf47f2-3c49-11e6-8b5b-8360d3ccd632.png">

**Comment by miconblog** [comment]
@limsungmook 이런 경우가 종종 있더라구요. 찾아보니까 페북 세션 문제라서 해결 방법도 없어요. 그냥 로그아웃 강제로 시키고 다시 로그인하라고 하더군요. ㅎㅎ 무슨 문젠지 모를테니 다시 로그인하라는 안내를 넣어야겠어요!

**Comment by miconblog** [comment]
아참 스크린샷 떠준거 너무 고마워요~ 👍

**Comment by limsungmook** [comment]
@miconblog 글쿤여! 코멘트 합니다. 말씀하신대로 안내 메시지라도 있으면 좋을 것 같아요~^^

**Comment by miconblog** [comment]
@limsungmook 해결하면 클로즈 할께요~

**Comment by miconblog** [comment]
@limsungmook 요건 해결되서 종료합니다.
