### ISSUE TITLE
노트에 이미지를 삽입하고 싶다

### ISSUE THREAD

**Issue by Aromi** [rlibro/feedback#86]
#### 요구사항 정리
1. 이미지가 삽입되면 지도 아이콘 옆에 보인다. 
   <img width="319" alt="2016-07-23 11 15 46" src="https://cloud.githubusercontent.com/assets/1381312/17078685/5c292dca-50c7-11e6-99f1-5ddba64d5626.png">
2. 삽입된 이미지도 타이틀이 있어서 타이틀을 본문에 삽입할수있다.
3. 노트에서 삽입된 이미지 타이틀을 클릭하거나 오른쪽 하단에 이미지 아이콘을 클릭하면 싱글 노트에 이미지가 보이는 형태로 이동한다. 
4. 싱글 노트에서  이미지 영역을 클릭하면 FullSize 이미지로 보여준다. (옵션)

**Comment by miconblog** [comment]
다음 버전 개발에 이미지 서버가 필요하니까 일단 노트당 1개씩만 해서 진행해요~

**Comment by miconblog** [comment]
@Aromi 이제 정보북 노트에서 이미지 삽입 할수있습니다. 삽입 방법은 깃헙 이슈와 동일합니다. 이미지 선택해서 업로드하면 본문에 자동 삽입됩니다.
